// src/constants/teamLogos.ts
export const TEAM_LOGOS_LB_URI =
  "https://storage.googleapis.com/cl-beta-428221-app-assets";

// Map team "display name" -> logo URL.
// Keep keys EXACTLY as your API returns them (case & spacing).
const teamLogos: Record<string, string> = {
  // MLB
  Guardians: `${TEAM_LOGOS_LB_URI}/mlb/guardians.png`,
  Orioles: `${TEAM_LOGOS_LB_URI}/mlb/orioles.png`,
  Phillies: `${TEAM_LOGOS_LB_URI}/mlb/phillies.png`,
  Tigers: `${TEAM_LOGOS_LB_URI}/mlb/tigers.png`,
  Mariners: `${TEAM_LOGOS_LB_URI}/mlb/mariners.png`,
  Rays: `${TEAM_LOGOS_LB_URI}/mlb/rays.png`,
  Yankees: `${TEAM_LOGOS_LB_URI}/mlb/yankees.png`,
  "Blue Jays": `${TEAM_LOGOS_LB_URI}/mlb/bluejays.png`,
  Mets: `${TEAM_LOGOS_LB_URI}/mlb/mets.png`,
  "Red Sox": `${TEAM_LOGOS_LB_URI}/mlb/redsox.png`,
  Pirates: `${TEAM_LOGOS_LB_URI}/mlb/pirates.png`,
  Reds: `${TEAM_LOGOS_LB_URI}/mlb/reds.png`,
  Braves: `${TEAM_LOGOS_LB_URI}/mlb/braves.png`,
  Cardinals: `${TEAM_LOGOS_LB_URI}/mlb/cardinals.png`,
  Marlins: `${TEAM_LOGOS_LB_URI}/mlb/marlins.png`,
  Royals: `${TEAM_LOGOS_LB_URI}/mlb/royals.png`,
  Dodgers: `${TEAM_LOGOS_LB_URI}/mlb/dodgers.png`,
  "White Sox": `${TEAM_LOGOS_LB_URI}/mlb/whitesox.png`,
  Rockies: `${TEAM_LOGOS_LB_URI}/mlb/rockies.png`,
  Astros: `${TEAM_LOGOS_LB_URI}/mlb/astros.png`,
  Rangers: `${TEAM_LOGOS_LB_URI}/mlb/rangers.png`,
  Brewers: `${TEAM_LOGOS_LB_URI}/mlb/brewers.png`,
  Athletics: `${TEAM_LOGOS_LB_URI}/mlb/athletics.png`,
  Angels: `${TEAM_LOGOS_LB_URI}/mlb/angels.png`,
  Twins: `${TEAM_LOGOS_LB_URI}/mlb/twins.png`,
  Diamondbacks: `${TEAM_LOGOS_LB_URI}/mlb/dbacks.png`,
  Nationals: `${TEAM_LOGOS_LB_URI}/mlb/nationals.png`,
  Padres: `${TEAM_LOGOS_LB_URI}/mlb/padres.png`,
  Cubs: `${TEAM_LOGOS_LB_URI}/mlb/cubs.png`,
  Giants: `${TEAM_LOGOS_LB_URI}/mlb/giants.png`,

  // NFL
  "Kansas City Chiefs": `${TEAM_LOGOS_LB_URI}/nfl/chiefs.png`,
  "San Francisco 49ers": `${TEAM_LOGOS_LB_URI}/nfl/49ers.png`,
  "Miami Dolphins": `${TEAM_LOGOS_LB_URI}/nfl/Dolphins.png`,
  "Houston Texans": `${TEAM_LOGOS_LB_URI}/nfl/Texans.png`,
  "New York Jets": `${TEAM_LOGOS_LB_URI}/nfl/Jets.png`,
  "Tennessee Titans": `${TEAM_LOGOS_LB_URI}/nfl/Titans.png`,
  "New Orleans Saints": `${TEAM_LOGOS_LB_URI}/nfl/Saints.png`,
  "Carolina Panthers": `${TEAM_LOGOS_LB_URI}/nfl/Panthers.png`,
  "Las Vegas Raiders": `${TEAM_LOGOS_LB_URI}/nfl/Raiders.png`,
  "New York Giants": `${TEAM_LOGOS_LB_URI}/nfl/Giants.png`,
  "Chicago Bears": `${TEAM_LOGOS_LB_URI}/nfl/Bears.png`,
  "Jacksonville Jaguars": `${TEAM_LOGOS_LB_URI}/nfl/Jaquars.png`,
  "Tampa Bay Buccaneers": `${TEAM_LOGOS_LB_URI}/nfl/Buccs.png`,
  "Atlanta Falcons": `${TEAM_LOGOS_LB_URI}/nfl/Falcons.png`,
  "Cincinnati Bengals": `${TEAM_LOGOS_LB_URI}/nfl/Bengals.png`,
  "Los Angeles Rams": `${TEAM_LOGOS_LB_URI}/nfl/Rams.png`,
  "Indianapolis Colts": `${TEAM_LOGOS_LB_URI}/nfl/Colts.png`,
  "Baltimore Ravens": `${TEAM_LOGOS_LB_URI}/nfl/Ravens.png`,
  "Green Bay Packers": `${TEAM_LOGOS_LB_URI}/nfl/Packers.png`,
  "Minnesota Vikings": `${TEAM_LOGOS_LB_URI}/nfl/Vikings.png`,
  "Buffalo Bills": `${TEAM_LOGOS_LB_URI}/nfl/Bills.png`,
  "Pittsburgh Steelers": `${TEAM_LOGOS_LB_URI}/nfl/Steelers.png`,
  "Detroit Lions": `${TEAM_LOGOS_LB_URI}/nfl/Lions.png`,
  "Los Angeles Chargers": `${TEAM_LOGOS_LB_URI}/nfl/Chargers.png`,
  "Dallas Cowboys": `${TEAM_LOGOS_LB_URI}/nfl/Cowboys.png`,
  "Cleveland Browns": `${TEAM_LOGOS_LB_URI}/nfl/Browns.png`,
  "Arizona Cardinals": `${TEAM_LOGOS_LB_URI}/nfl/Cardinals.png`,
  "Denver Broncos": `${TEAM_LOGOS_LB_URI}/nfl/Broncos.png`,
  "Seattle Seahawks": `${TEAM_LOGOS_LB_URI}/nfl/Seahawks.png`,
  "Philadelphia Eagles": `${TEAM_LOGOS_LB_URI}/nfl/Eagles.png`,
  "New England Patriots": `${TEAM_LOGOS_LB_URI}/nfl/Patriots.png`,
  "Washington Commanders": `${TEAM_LOGOS_LB_URI}/nfl/Commanders.png`,

  // NHL
  "Edmonton Oilers": `${TEAM_LOGOS_LB_URI}/nhl/Oilers.png`,
  "Florida Panthers": `${TEAM_LOGOS_LB_URI}/nhl/Panthers.png`,
  "Anaheim Ducks": `${TEAM_LOGOS_LB_URI}/nhl/Ducks.png`,
  "Los Angeles Kings": `${TEAM_LOGOS_LB_URI}/nhl/Kings.png`,
  "Nashville Predators": `${TEAM_LOGOS_LB_URI}/nhl/Predators.png`,
  "San Jose Sharks": `${TEAM_LOGOS_LB_URI}/nhl/Sharks.png`,
  "Calgary Flames": `${TEAM_LOGOS_LB_URI}/nhl/Flames.png`,
  "Seattle Kraken": `${TEAM_LOGOS_LB_URI}/nhl/Kraken.png`,
  "Minnesota Wild": `${TEAM_LOGOS_LB_URI}/nhl/Wild.png`,
  "Dallas Stars": `${TEAM_LOGOS_LB_URI}/nhl/Stars.png`,
  "Carolina Hurricanes": `${TEAM_LOGOS_LB_URI}/nhl/Canes.png`,
  "Vancouver Canucks": `${TEAM_LOGOS_LB_URI}/nhl/Canucks.png`,
  "Boston Bruins": `${TEAM_LOGOS_LB_URI}/nhl/Bruins.png`,
  "Vegas Golden Knights": `${TEAM_LOGOS_LB_URI}/nhl/Knights.png`,
  "Ottowa Senators": `${TEAM_LOGOS_LB_URI}/nhl/Senators.png`,
  "Washington Capitals": `${TEAM_LOGOS_LB_URI}/nhl/Capitals.png`,
  "Toronto Maple Leafs": `${TEAM_LOGOS_LB_URI}/nhl/Leafs.png`,
  "Colorado Avalanche": `${TEAM_LOGOS_LB_URI}/nhl/Avalanche.png`,
  "New York Rangers": `${TEAM_LOGOS_LB_URI}/nhl/Rangers.png`,
  "Philadelphia Flyers": `${TEAM_LOGOS_LB_URI}/nhl/Flyers.png`,
  "New York Islanders": `${TEAM_LOGOS_LB_URI}/nhl/Islanders.png`,
  "New Jersey Devils": `${TEAM_LOGOS_LB_URI}/nhl/Devils.png`,
  "Tampa Bay Lightning": `${TEAM_LOGOS_LB_URI}/nhl/Lightning.png`,
  "St. Louis Blues": `${TEAM_LOGOS_LB_URI}/nhl/Blues.png`,
  "Montreal Canadiens": `${TEAM_LOGOS_LB_URI}/nhl/Canadiens.png`,
  "Detroit Red Wings": `${TEAM_LOGOS_LB_URI}/nhl/RedWings.png`,
  "Buffalo Sabres": `${TEAM_LOGOS_LB_URI}/nhl/Sabres.png`,
  "Columbus Blue Jackets": `${TEAM_LOGOS_LB_URI}/nhl/BlueJackets.png`,
  "Winnipeg Jets": `${TEAM_LOGOS_LB_URI}/nhl/Jets.png`,
  "Chicago Blackhawks": `${TEAM_LOGOS_LB_URI}/nhl/Blackhawks.png`,
  "Arizona Coyotes": `${TEAM_LOGOS_LB_URI}/nhl/Coyotes.png`,
  "Pittsburgh Penguins": `${TEAM_LOGOS_LB_URI}/nhl/Penguins.png`,

  // NBA
  "Dallas Mavericks": `${TEAM_LOGOS_LB_URI}/nba/mavs.png`,
  "Boston Celtics": `${TEAM_LOGOS_LB_URI}/nba/celtics.png`,
  "Miami Heat": `${TEAM_LOGOS_LB_URI}/nba/heat.png`,
  "Atlanta Hawks": `${TEAM_LOGOS_LB_URI}/nba/Hawks.png`,
  "Los Angeles Lakers": `${TEAM_LOGOS_LB_URI}/nba/Lakers.png`,
  "Cleveland Cavaliers": `${TEAM_LOGOS_LB_URI}/nba/calvs.png`,
  "Sacramento Kings": `${TEAM_LOGOS_LB_URI}/nba/kings.png`,
  "Orlando Magic": `${TEAM_LOGOS_LB_URI}/nba/magic.png`,
  "Brooklyn Nets": `${TEAM_LOGOS_LB_URI}/nba/nets.png`,
  "Phoenix Suns": `${TEAM_LOGOS_LB_URI}/nba/suns.png`,
  "Minnesota Timberwolves": `${TEAM_LOGOS_LB_URI}/nba/timberwolves.png`,
  "Washington Wizards": `${TEAM_LOGOS_LB_URI}/nba/wizards.png`,
  "Philadelphia 76ers": `${TEAM_LOGOS_LB_URI}/nba/76ers.png`,
  "Milwaukee Bucks": `${TEAM_LOGOS_LB_URI}/nba/bucks.png`,
  "Toronto Raptors": `${TEAM_LOGOS_LB_URI}/nba/raptors.png`,
  "Charlotte Hornets": `${TEAM_LOGOS_LB_URI}/nba/hornets.png`,
  "Houston Rockets": `${TEAM_LOGOS_LB_URI}/nba/rockets.png`,
  "LA Clippers": `${TEAM_LOGOS_LB_URI}/nba/clippers.png`,
  "Indiana Pacers": `${TEAM_LOGOS_LB_URI}/nba/pacers.png`,
  "Detroit Pistons": `${TEAM_LOGOS_LB_URI}/nba/pistons.png`,
  "Chicago Bulls": `${TEAM_LOGOS_LB_URI}/nba/bulls.png`,
  "New Orleans Pelicans": `${TEAM_LOGOS_LB_URI}/nba/pelicans.png`,
  "Memphis Grizzlies": `${TEAM_LOGOS_LB_URI}/nba/grizzlies.png`,
  "Utah Jazz": `${TEAM_LOGOS_LB_URI}/nba/jazz.png`,
  "Golden State Warriors": `${TEAM_LOGOS_LB_URI}/nba/warriors.png`,
  "Portland Trail Blazers": `${TEAM_LOGOS_LB_URI}/nba/blazers.png`,
  "New York Knicks": `${TEAM_LOGOS_LB_URI}/nba/knicks.png`,
  "Denver Nuggets": `${TEAM_LOGOS_LB_URI}/nba/nuggets.png`,
  "San Antonio Spurs": `${TEAM_LOGOS_LB_URI}/nba/spurs.png`,
  "Oklahoma City Thunder": `${TEAM_LOGOS_LB_URI}/nba/thunder.png`,
};

export function getTeamLogo(name?: string | null): string | undefined {
  if (!name) return undefined;
  return teamLogos[name] ?? undefined;
}

export default teamLogos;
